-- Generated by getPostgresMigration. Apply once in a transaction using your migration runner.

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public"."webhook_schema_version" (version integer PRIMARY KEY);
INSERT INTO "public"."webhook_schema_version" VALUES (3);

CREATE TABLE "public"."webhook_endpoint_state" (
  scope_key text NOT NULL,
  endpoint_id text NOT NULL,
  max_in_flight integer NOT NULL DEFAULT 2 CHECK (max_in_flight BETWEEN 1 AND 50),
  PRIMARY KEY (scope_key,endpoint_id)
);

CREATE TABLE "public"."webhook_events" (
  id uuid PRIMARY KEY,
  scope_key text NOT NULL,
  type text NOT NULL,
  body text NOT NULL,
  fingerprint text NOT NULL,
  idempotency_key text,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  UNIQUE (scope_key,id),
  UNIQUE (scope_key,idempotency_key)
);
CREATE INDEX webhook_events_retention ON "public"."webhook_events"(created_at,id);

CREATE TABLE "public"."webhook_deliveries" (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  scope_key text NOT NULL,
  endpoint_id text NOT NULL,
  event_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','in_flight','succeeded','failed','cancelled')),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  next_attempt_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  preparing boolean NOT NULL DEFAULT false,
  claim_token uuid,
  lease_expires_at timestamptz,
  replay_of bigint,
  last_error text,
  last_status integer,
  created_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  UNIQUE (scope_key,id),
  FOREIGN KEY (scope_key,replay_of) REFERENCES "public"."webhook_deliveries"(scope_key,id) ON DELETE CASCADE,
  FOREIGN KEY (scope_key,endpoint_id) REFERENCES "public"."webhook_endpoint_state"(scope_key,endpoint_id),
  FOREIGN KEY (scope_key,event_id) REFERENCES "public"."webhook_events"(scope_key,id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX webhook_deliveries_original ON "public"."webhook_deliveries"(event_id,endpoint_id) WHERE replay_of IS NULL;
CREATE UNIQUE INDEX webhook_deliveries_active_replay ON "public"."webhook_deliveries"(replay_of) WHERE replay_of IS NOT NULL AND status IN ('pending','in_flight');
CREATE INDEX webhook_deliveries_due ON "public"."webhook_deliveries"(next_attempt_at,id) WHERE status='pending';
CREATE INDEX webhook_deliveries_leases ON "public"."webhook_deliveries"(lease_expires_at) WHERE status='in_flight';
CREATE INDEX webhook_deliveries_endpoint ON "public"."webhook_deliveries"(scope_key,endpoint_id,status,id);
CREATE INDEX webhook_deliveries_scope ON "public"."webhook_deliveries"(scope_key,id DESC);
CREATE INDEX webhook_deliveries_event ON "public"."webhook_deliveries"(event_id);

CREATE TABLE "public"."webhook_attempts" (
  delivery_id bigint NOT NULL REFERENCES "public"."webhook_deliveries"(id) ON DELETE CASCADE,
  number integer NOT NULL CHECK (number > 0),
  started_at timestamptz NOT NULL DEFAULT statement_timestamp(),
  finished_at timestamptz,
  outcome text NOT NULL DEFAULT 'started' CHECK (outcome IN ('started','succeeded','retry','failed','abandoned')),
  response_status integer,
  response_body text,
  error text,
  PRIMARY KEY (delivery_id,number)
);
