-- Generated by getPostgresMigration. Apply once in a transaction using your migration runner.

CREATE SCHEMA IF NOT EXISTS "public";

CREATE TABLE "public"."webhook_endpoints" (
  id text PRIMARY KEY,
  scope_key text NOT NULL,
  url text NOT NULL,
  description text,
  event_types text[] NOT NULL CHECK (cardinality(event_types) BETWEEN 1 AND 100),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'paused', 'deleted')),
  secret text NOT NULL,
  previous_secret text,
  previous_secret_expires_at timestamptz,
  revision integer NOT NULL DEFAULT 0 CHECK (revision >= 0),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  CHECK ((previous_secret IS NULL) = (previous_secret_expires_at IS NULL)),
  CHECK (status <> 'deleted' OR (secret = '' AND previous_secret IS NULL))
);

CREATE INDEX webhook_endpoints_scope_idx ON "public"."webhook_endpoints"(scope_key)
  WHERE status <> 'deleted';
